
def guess_name(name):
    names = filter(lambda x,n=name:n.lower() in x.lower(),full_to_abbr.keys())
    if len(names) == 1: return full_to_abbr[names[0]]
    if len(names) > 1: return None
    # no match, try just the first word
    names = filter(lambda x,n=name:n.lower().split()[0] in x.lower().split()[0],full_to_abbr.keys())
    if len(names) == 1: return full_to_abbr[names[0]]
    print "couldn't match: %s "%name
    return None



full_to_abbr = {'Campbell Fighting Camels':'CAMP',
    'Robert Morris Colonials':'RMOR',
    'East Tennessee State Buccaneers':'ETSU',
    'Central Connecticut State Blue Devils':'CCONN',
    'Incarnate Word Cardinals':'IW',
    'Holy Cross Crusaders':'HC',
    'Houston Baptist Huskies':'HBU',
    'UAB Blazers':'UAB',
    'Monmouth Hawks':'MONM',
    'Mercer Bears':'MER',
     'North Carolina A&T Aggies':'NCAT',
    'San Diego Toreros':'SDT',
    'Albany Great Danes':'ALBY',
    'Abilene Christian Wildcats':'ACU',
    'North Dakota':'NDU',
    'North Dakota Fighting Hawks':'NDU',
    'Mississippi Valley State Delta Devils':'MVSU',
    'Bucknell Bison':'BUCK',
    'Charlotte 49ers':'CHAR',
'Texas Tech Red Raiders':'TXT',
'Prairie View A&M Panthers': 'PRVW',
 'Florida State Seminoles': 'FLST',
 'Idaho Vandals': 'IDA',
 'Purdue Boilermakers': 'PUR',
 'Vanderbilt Commodores': 'VAN',
 'North Dakota Fighting Sioux': 'NDST',
    'Southern Mississippi Golden Eagles': 'SMIS',
 'Alabama State Hornets': 'ASU',
    'Murray State Racers': 'MUR',
 'Texas Southern Tigers': 'TXSO',
 'Arizona Wildcats': 'ARZ',
 'Louisiana State Tigers': 'LSU',
 'Tennessee Tech Golden Eagles': 'TENT',
 'SE Missouri State Redhawks': 'SEMS',
 'Utah Utes': 'UTAH',
 'Nevada Wolf Pack': 'NEV',
 'Grambling State Tigers': 'GRAM',
 'Fresno State Bulldogs': 'FRES',
 'Charleston Southern Buccaneers': 'CHSO',
 'East Carolina Pirates': 'ECAR',
 'Texas Christian Horned Frogs': 'TCU',
 'Miami Ohio Redhawks': 'MIAO',
 'Bethune Cookman Wildcats': 'BCU',
 'California Golden Bears': 'CAL',
 'Austin Peay Governors': 'PEAY',
 'Gardner Webb Bulldogs': 'GWU',
 'Hampton Pirates': 'HAM',
 'Michigan Wolverines': 'MICH',
 'Florida Atlantic Owls': 'FATL',
 'Duke Blue Devils': 'DUKE',
 'Bowling Green Falcons': 'BOWL',
 'Southern California Trojans': 'USC',
 'San Jose State Spartans': 'SJST',
 'Utah State Aggies': 'UTST',
 'Minnesota Golden Gophers': 'MIN',
 'Ball State Cardinals': 'BALL',
 'Morgan State Bears': 'MORG',
 'Howard Bison': 'HOW',
 'Auburn Tigers': 'AUB',
 'Navy Midshipmen': 'NAVY',
 'Colorado Buffaloes': 'COLO',
 'Northwestern Wildcats': 'NORW',
 'Virginia Military Keydets': 'VMI',
 'Rutgers Scarlet Knights': 'RUT',
 'Eastern Washington Eagles': 'EWA',
'Washington State Cougars':'WAST',
 'Northwestern State Demons': 'NOST',
 'Georgia Bulldogs': 'GEO',
 'Stephen Austin Lumberjacks': 'SFAN',
 'Washington Huskies': 'WAS',
 'North Carolina Tar Heels': 'NCAR',
 'Richmond Spiders': 'RICH',
 'Kent State Golden Flashes': 'KEST',
 'South Florida Bulls': 'SFL',
 'Middle Tennessee St Blue Raiders': 'MTEN',
 'Oklahoma State Cowboys': 'OKST',
 'Charles Southern Buccaneers': 'CHSO',
 'Liberty Flames': 'LIB',
 'Portland State Vikings': 'POST',
 'Buffalo Bulls': 'BUF',
 'Alcorn State Braves': 'ALCN',
 'Cal Poly SLO Mustangs': 'CPOL',
 'Tennessee Chattanooga Moccasins': 'TCHA',
 'South Carolina State Bulldogs': 'SCST',
 'Ark Pine Bluff Golden Lions': 'ARKP',
 'San Diego State Aztecs': 'SDST',
 'San Diego State': 'SDST',
 'Boise State Broncos': 'BOIS',
 'Army Black Knights': 'ARMY',
 'Western Carolina Catamounts': 'WCAR',
 'Northern Illinois Huskies': 'NIL',
 'Texas San Antonio Roadrunners': 'UTSA',
 'Illinois Fighting Illini': 'ILL',
 'Iowa Hawkeyes': 'IOWA',
 'West Virginia Mountaineers': 'WVA',
 'Louisville Cardinals': 'LOU',
 'Delaware Fightin Blue Hens': 'DEL',
 'Western Michigan Broncos': 'WMCH',
 'Rice Owls': 'RICE',
 'Kansas Jayhawks': 'KAN',
 'North Dakota State Bison': 'NDST',
 'Southern Methodist Mustangs': 'SMU',
 'Sam Houston State Bearkats': 'SHST',
 'Alabama Birmingham Blazers': 'UAB',
 'UC Davis Aggies': 'CDAV',
 'Syracuse Orange': 'SYR',
 'Virginia Cavaliers': 'VIR',
 'Mississippi Rebels': 'MIS',
 'Louisiana Tech Bulldogs': 'LTCH',
 'Texas A&M Aggies': 'TXAM',
 'Brigham Young Cougars': 'BYU',
 'North Carolina Central Eagles': 'NCC',
 'Citadel Bulldogs': 'CTDL',
 'South Dakota St': 'SDKS',
 'South Dakota State': 'SDKS',
 'UCLA Bruins': 'UCLA',
 'Wagner Seahawks': 'WAG',
 'Stephen F Austin Lumberjacks': 'SFAN',
 'Weber State Wildcats': 'WEB',
 'Southern Utah Thunderbirds': 'SUT',
 'Hofstra Flying Dutchmen': 'HOF',
 'Tulane Green Wave': 'TLN',
 'Connecticut Huskies': 'CON',
 'Hawaii Warriors': 'HAW',
 'Central Michigan Chippewas': 'CMCH',
 'Eastern Michigan Eagles': 'EMCH',
 'Tennessee Martin Skyhawks': 'TMAR',
 'Eastern Kentucky Colonels': 'EKY',
 'Middle Tennessee State Blue Raiders': 'MTEN',
 'Central Florida Knights': 'CFL',
 'South Dakota Coyotes': 'USD',
 'Montana Grizzlies': 'MONT',
 'Notre Dame Fighting Irish': 'NOTD',
 'Villanova Wildcats': 'VIL',
 'Samford Bulldogs': 'SAMF',
 'UL Lafayette Ragin Cajuns': 'LLAF',
 'Central Conn Blue Devils': 'CCST',
 'Jackson State Tigers': 'JAST',
 'Tennessee State Tigers': 'TNST',
 'Alabama Crimson Tide': 'ALA',
 'South Carolina Gamecocks': 'SCAR',
 'Arkansas State Red Wolves': 'AKST',
 'UNLV Rebels': 'UNLV',
 'Presbyterian Blue Hose': 'PRES',
 'Colgate Red Raiders': 'CLG',
 'Lamar Cardinals': 'LAMA',
 'Indiana Hoosiers': 'IND',
 'Ohio Bobcats': 'OHU',
 'Air Force Falcons': 'AIR',
 'North Carolina State Wolfpack': 'NCST',
    'NC State Wolfpack':'NCST',
 'Georgia State Panthers': 'GAST',
 'James Madison Dukes': 'JMAD',
 'Florida International Golden Panthers': 'FINT',
 'Northern Colorado Bears': 'NCOL',
 'Georgia Tech Yellow Jackets': 'GTCH',
 'Middle Tennessee Blue Raiders': 'MTEN',
 'Oregon Ducks': 'ORE',
 'Fordham Rams': 'FORD',
 'Western Illinois Leathernecks': 'WIL',
 'Missouri Tigers': 'MIZ',
 'Nicholls State Colonels': 'NICH',
 'Gardner Webb Runnin Bulldogs': 'GWU',
 'North Texas Mean Green': 'NTX',
 'UL Monroe Warhawks': 'LMON',
 'Missouri State Bears': 'SWMS',
 'Elon University Phoenix': 'ELON',
 'Maine Black Bears': 'MAIN',
 'Boston College Eagles': 'BCOL',
 'Idaho State Bengals': 'IDST',
 'Mississippi State Bulldogs': 'MSST',
 'Jacksonville State Gamecocks': 'JVST',
 'Florida Gators': 'FLA',
 'Hawaii Rainbow Warriors': 'HAW',
 'Furman Paladins': 'FUR',
 'Western Kentucky Hilltoppers': 'WKY',
 'Penn State Nittany Lions': 'PNST',
 'Southeastern Louisiana Lions': 'SELA',
 'Norfolk State Spartans': 'NFST',
 'UNLV Runnin Rebels': 'UNLV',
 'Memphis Tigers': 'MEM',
 'Oregon State Beavers': 'ORST',
 'Wyoming Cowboys': 'WYO',
 'Coastal Carolina Chanticleers': 'CSTC',
 'Youngstown State Penguins': 'YST',
 'Miss Valley St Delta Devils': 'MSVT',
 'New Mexico State Aggies': 'NMST',
 'Northeastern Huskies': 'NEAS',
 'Indiana State Sycamores': 'INST',
 'Wisconsin Badgers': 'WIS',
 'Wofford Terriers': 'WOF',
 'South Dakota State Jackrabbits': 'SDKS',
 'Wake Forest Demon Deacons': 'WAKE',
 'New Mexico Lobos': 'NMX',
 'Houston Cougars': 'HOU',
 'Montana State Bobcats': 'MONS',
 'Colorado State Rams': 'COST',
 'Tennessee Volunteers': 'TEN',
 'Arkansas Pine Bluff Golden Lions': 'AKPB',
 'Ohio State Buckeyes': 'OHST',
 'Towson Tigers': 'TWSN',
 'Northern Arizona Lumberjacks': 'NAZ',
 'Florida A&M Rattlers': 'FAM',
 'South Alabama Jaguars': 'SALA',
 'Virginia Tech Hokies': 'VTCH',
 'Prairie View Panthers': 'PVAM',
 'Delaware Blue Hens': 'DEL',
 'Troy Trojans': 'TROY',
 'Toledo Rockets': 'TOL',
 'New Hampshire Wildcats': 'NHAM',
 'Georgia Southern Eagles': 'GSOU',
 'Tulsa Golden Hurricane': 'TLS',
 'Arkansas Razorbacks': 'ARK',
 'Clemson Tigers': 'CLEM',
 'Delaware State Hornets': 'DEL',
 'Appalachian State Mountainers': 'APP',
 'Texas Longhorns': 'TEX',
 'Massachusetts Minutemen': 'MAS',
 'Cincinnati Bearcats': 'CIN',
 'Marshall Thundering Herd': 'MRSH',
 'Savannah State Tigers': 'SAVA',
 'Tenn Martin Skyhawks': 'TMAR',
 'Maryland Terrapins': 'MARY',
 'Michigan State Spartans': 'MCST',
 'Central Arkansas Bears': 'CARK',
 'Rhode Island Rams': 'RISL',
 'Pittsburgh Panthers': 'PIT',
 'Sacramento State Hornets': 'CSAC',
 'Illinois State Redbirds': 'ILST',
 'Baylor Bears': 'BAY',
 'Old Dominion Monarchs': 'OLDD',
 'Iowa State Cyclones': 'IWST',
 'Northern Iowa Panthers': 'NIWA',
 'Miami Hurricanes': 'MIAF',
 'McNeese State Cowboys': 'MNEE',
 'Stony Brook Sea Wolves': 'STBR',
 'Oklahoma Sooners': 'OKLA',
 'Texas El Paso Miners': 'UTEP',
 'Stanford Cardinal': 'STAN',
 'Arizona State Sun Devils': 'AZST',
 'Kansas State Wildcats': 'KAST',
 'Kentucky Wildcats': 'KTKY',
 'Southern Jaguars': 'SOU',
 'Southern Illinois Salukis': 'SIL',
 'William & Mary Tribe': 'WAM',
 'Alabama A&M Bulldogs': 'ALAM',
 'Chattanooga Mocs': 'TCHA',
 'Temple Owls': 'TEM',
 'Nebraska Cornhuskers': 'NEB',
 'Texas State Bobcats': 'TXST',
 'Appalachian State Mountaineers': 'APP',
 'Akron Zips': 'AKRON',
 'Eastern Illinois Panthers': 'EIL'}

abbr_to_full = {}
for f in full_to_abbr.keys():
    abbr_to_full[full_to_abbr[f]] = f

# built by hand to start the 2014 season.
# if trouble, consider mapping school name from schedule to full name in (previous) box scores.
alias_to_abbr = {
    'USM':'SMIS',
    'SWTX':'TXST',
    'TEST':'TNST',
    'HAR':'HVD',
    'CC':'CSTC',
    'MSVT':'MVST',
    'APEA':'PEAY',
    'HC':'HCR',
    'ALCST':'ALCN',
    'ALCS':'ALCN',
    'GSU': 'GAST',
 'SIU': 'SIL',
 'BC': 'BCOL',
 'MIA': 'MIAF',
 'SJSU': 'SJST',
 'SHSU': 'SHST',
 'NAU': 'NAZ',
 'NDSU': 'NDST',
 'JMU': 'JMAD',
 'CONN': 'CON',
 'PRE': 'PRES',
 'SAM': 'SAMF',
 'PITT': 'PIT',
 'ARIZ': 'ARZ',
 'IDHO': 'IDA',
 'TAM': 'TXAM',
 'SAV': 'SAVA',
 'GT': 'GTCH',
 'FIU': 'FINT',
 'CCAR': 'CSTC',
 'FAMU': 'FAM',
 'WMU': 'WMCH',
 'NCCU': 'NCC',
 'MURR': 'MUR',
 'BGSU': 'BOWL',
 'STON': 'STBR',
 'MIZZ': 'MIZ',
 'TULN': 'TLN',
 'MCNS': 'MNEE',
 'NORF': 'NFST',
 'TOWS': 'TWSN',
 'NIU': 'NIL',
 'KSU': 'KAST',
 'GASO': 'GSOU',
 'EMU': 'EMCH',
 'COLG': 'CLG',
 'CMU': 'CMCH',
 'YSU': 'YST',
 'PV': 'PRVW',
 'UGA': 'GEO',
 'OSU': 'OHST',
 'TTU': 'TXT',
 'TXTCH': 'TXT',
 'WVU': 'WVA',
 'SOUTH': 'SOU',
 'UVA': 'VIR',
 'FOR': 'FORD',
 'TLSA': 'TLS',
 'AFA': 'AIR',
 'VILL': 'VIL',
 'JKST': 'JAST',
 'CSU': 'COST',
 'SOMIS': 'SMIS',
 'MTU': 'MTEN',
 'MISS': 'MIS',
 'EWU': 'EWA',
 'ME': 'MAIN',
 'MD': 'MARY',
 'TENN': 'TEN',
 'SOCAR': 'SCAR',
 'MOH': 'MIAO',
 'KENT': 'KEST',
 'SFA': 'SFAN',
 'PSU': 'PNST',
 'WEBB': 'GWU',
 'CSUS': 'CSAC',
 'TNTC': 'TENT',
 'AKR': 'AKRON',
 'ISU': 'IWST',
 'SDAK': 'USD',
 'SUU': 'SUT',
 'FSU': 'FLST',
 'CHAT': 'TCHA',
 'ASU': 'AZST',
 'LAM': 'LAMA',
 'BSU': 'BOIS',
 'ND': 'NOTD',
 'ODU': 'OLDD',
 'ECU': 'ECAR',
 'MASS': 'MAS',
 'NW': 'NORW',
 'UNT': 'NTX',
 'MINN': 'MIN',
 'UNC': 'NCAR',
 'UNH': 'NHAM',
 'UNI': 'NIWA',
 'CP': 'CPOL',
 'CPO': 'CPOL',
 'UNM': 'NMX',
 'WIU': 'WIL',
 'KU': 'KAN',
 'SEMST': 'SEMS',
 'USF': 'SFL',
 'EIU': 'EIL',
 'USA': 'SALA',
 'MSU': 'MCST',
 'MTST': 'MONS',
 'PRST': 'POST',
 'WASH': 'WAS',
 'USU': 'UTST',
 'WSU': 'WAST',
 'CIT': 'CTDL',
 'ALST': 'ASU',
 'FAU': 'FATL',
 'UCF': 'CFL',
 'LT': 'LTCH',
 'UCD': 'CDAV',
 'OHIO': 'OHU',
 'UNCO': 'NCOL',
 'BUFF': 'BUF',
 'WCU': 'WCAR',
 'UK': 'KTKY',
 'UTM': 'TMAR',
 'MOSU': 'SWMS',
 'CWM': 'WAM',
 'ULL': 'LLAF',
 'ULM': 'LMON',
 'ULMON': 'LMON',
 'NMSU': 'NMST',
 'RUTG': 'RUT',
 'WKU': 'WKY',
 'NWST':'NOST',
 'VT':'VTCH',
 'ARST':'AKST',
    'SDSU':'SDST',
    'GRA':'GRAM',
    'GAR':'GRAM',
    'CCONN':'CCON',
    'ECR':'ECAR',
    'GWU':'GARD',
    'CCU':'CSTC',
    'ARPB':'AKPB',
    'BCU':'COOK',
                 }
